export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SET_TOKEN = 'SET_TOKEN';

export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';

export const POST_QUESTIONS_REQUEST = 'POST_QUESTIONS_REQUEST';
export const POST_QUESTIONS_SUCCESS = 'POST_QUESTIONS_SUCCESS';
export const POST_QUESTIONS_FAILURE = 'POST_QUESTIONS_FAILURE';

export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

export const GET_CURRENT_HISTORY_REQUEST = 'GET_CURRENT_HISTORY_REQUEST';
export const GET_CURRENT_HISTORY_SUCCESS = 'GET_CURRENT_HISTORY_SUCCESS';
export const GET_CURRENT_HISTORY_FAILURE = 'GET_CURRENT_HISTORY_FAILURE';

export const GET_ANSWER_BY_PASS_REQUEST = 'GET_ANSWER_BY_PASS_REQUEST';
export const GET_ANSWER_BY_PASS_SUCCESS = 'GET_ANSWER_BY_PASS_SUCCESS';
export const GET_ANSWER_BY_PASS_FAILURE = 'GET_ANSWER_BY_PASS_FAILURE';

export const GET_HISTORY_BY_PASS_REQUEST = 'GET_HISTORY_BY_PASS_REQUEST';
export const GET_HISTORY_BY_PASS_SUCCESS = 'GET_HISTORY_BY_PASS_SUCCESS';
export const GET_HISTORY_BY_PASS_FAILURE = 'GET_HISTORY_BY_PASS_FAILURE';

export const GET_HISTORY_BY_USERNAME_REQUEST = 'GET_HISTORY_BY_USERNAME_REQUEST';
export const GET_HISTORY_BY_USERNAME_SUCCESS = 'GET_HISTORY_BY_USERNAME_SUCCESS';
export const GET_HISTORY_BY_USERNAME_FAILURE = 'GET_HISTORY_BY_USERNAME_FAILURE';

export const CLEAR_PASS = 'CLEAR_PASS';
export const CLEAR_USERNAME = 'CLEAR_USERNAME';

export const GET_USER_SCREENING_HISTORY_REQUEST = 'GET_USER_SCREENING_HISTORY_REQUEST';
export const GET_USER_SCREENING_HISTORY_SUCCESS = 'GET_USER_SCREENING_HISTORY_SUCCESS';
export const GET_USER_SCREENING_HISTORY_FAILURE = 'GET_USER_SCREENING_HISTORY_FAILURE';

export const SAVE_SELECTED_USER = 'SAVE_SELECTED_USER';

export const GET_IMAGE_REQUEST = 'GET_IMAGE_REQUEST';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAILURE = 'GET_IMAGE_FAILURE';

export const CLEAR_USER_HISTORY = 'CLEAR_USER_HISTORY';
