export default {
  logo: require('../../assets/images/logo.png'),
  about: require('../../assets/images/about.png'),
  logout: require('../../assets/images/logout.png'),
  noResult: require('../../assets/images/noResult.png'),
  softteco: require('../../assets/images/softteco.png'),
  kandasoft: require('../../assets/images/kandasoft.png'),
  person: require('../../assets/images/person.png'),
  success: require('../../assets/images/success.png'),
  declined: require('../../assets/images/declined.png'),
  sik_men: require('../../assets/images/sik_men.png'),
  positiveIcon: require('../../assets/images/positiveIcon.png'),
  negativeIcon: require('../../assets/images/negativeIcon.png'),
  close: require('../../assets/images/close.png'),
  back: require('../../assets/images/back.png'),
};
